dumb-frotz: main.c buffer.o dumb-init.o dumb-input.o dumb-output.o dumb-pic.o fastmem.o files.o hotkey.o input.o math.o object.o process.o random.o redirect.o screen.o sound.o stream.o table.o text.o variable.o profiling.o frotz.h
	gcc -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -o dumb-frotz main.c *.o

buffer.o: buffer.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c buffer.c

dumb-init.o: dumb-init.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c dumb-init.c

dumb-input.o: dumb-input.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c dumb-input.c

dumb-output.o: dumb-output.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c dumb-output.c

dumb-pic.o: dumb-pic.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c dumb-pic.c

dumb-pic.o: dumb-pic.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c dumb-pic.c

fastmem.o: fastmem.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c fastmem.c

files.o: files.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c files.c

hotkey.o: hotkey.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c hotkey.c

input.o: input.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c input.c

math.o: math.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c math.c

object.o: object.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c object.c

process.o: process.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c process.c

random.o: random.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c random.c

redirect.o: redirect.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c redirect.c

screen.o: screen.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c screen.c

sound.o: sound.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c sound.c

stream.o: stream.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c stream.c

table.o: table.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c table.c

text.o: text.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c text.c

variable.o: variable.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c variable.c

profiling.o: profiling.c frotz.h
	gcc -c -mmacosx-version-min=10.3.9 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk -ansi -g -c profiling.c
