Title: inform7
Author: Graham Nelson
Build Date: 24 February 2019
Build Number: 6Q21
Version Name: Krypton
Version Number: 7.10.1
Purpose: The core compiler in a natural-language design system for interactive fiction.
Language: InC
Preform Language: English
Declare Section Usage: Off
Web Syntax Version: 2
Licence: Artistic License 2.0

Preliminaries
	Preface
	Licence and Copyright Declaration
	Introduction to Syntax ^"Preform"
	The Champollion Project

Import: foundation
Import: words
Import: inflections
Import: syntax
Import: problems
Import: linguistics
Import: kinds
Import: inter/inter
Import: core
Import: inter/codegen
Import: if
Import: multimedia
Import: index

Chapter 1: Delegation
	Main

Appendix A: The Standard Rules (Independent Inform 7)
"This is the body of Inform 7 source text automatically included with every
project compiled, and which defines most of what end users see as the Inform
language."
	Preamble
	Physical World Model
	Variables and Rulebooks
	Activities
	Actions
	Phrase Definitions

Appendix B: The Template Layer
"The template organises the I6 code generated by Inform, fleshes it out with
a large amount of standard material (similar to the content of the traditional
I6 library, which I7 doesn't use), and also controls the sequence of operations
followed during compilation."
	Introduction Template (Independent Inform 6)
	Main Template (Independent Inform 6)
	Load-Core Template (Independent Inform 6)
	Load-Times Template (Independent Inform 6)
	Load-Actions Template (Independent Inform 6)
	Load-Scenes Template (Independent Inform 6)
	Load-Figures Template (Independent Inform 6)
	Load-Sounds Template (Independent Inform 6)
	Load-Files Template (Independent Inform 6)
	Output Template (Independent Inform 6)
	Output-Stub Template (Independent Inform 6)
	Definitions Template (Independent Inform 6)
	OrderOfPlay Template (Independent Inform 6)
	Actions Template (Independent Inform 6)
	Activities Template (Independent Inform 6)
	Rulebooks Template (Independent Inform 6)
	Parser Template (Independent Inform 6)
	ListWriter Template (Independent Inform 6)
	OutOfWorld Template (Independent Inform 6)
	WorldModel Template (Independent Inform 6)
	Light Template (Independent Inform 6)
	Tests Template (Independent Inform 6)
	Language Template (Independent Inform 6)
	MStack Template (Independent Inform 6)
	Chronology Template (Independent Inform 6)
	Printing Template (Independent Inform 6)
	RTP Template (Independent Inform 6)
	Utilities Template (Independent Inform 6)
	Number Template (Independent Inform 6)
	Time Template (Independent Inform 6)
	Tables Template (Independent Inform 6)
	Sort Template (Independent Inform 6)
	Relations Template (Independent Inform 6)
	Figures Template (Independent Inform 6)
	Text Template (Independent Inform 6)
	RegExp Template (Independent Inform 6)
	Char Template (Independent Inform 6)
	UnicodeData Template (Independent Inform 6)
	StoredAction Template (Independent Inform 6)
	Lists Template (Independent Inform 6)
	Combinations Template (Independent Inform 6)
	RelationKind Template (Independent Inform 6)
	BlockValues Template (Independent Inform 6)
	Flex Template (Independent Inform 6)
	ZMachine Template (Independent Inform 6)
	Glulx Template (Independent Inform 6)
	FileIO Template (Independent Inform 6)

